<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.8 setup script
 * Date: Fri, 01 Nov 2013 16:35:01 -0400
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['controluser'] = 'root';
$cfg['Servers'][$i]['controlpass'] = 'password';
$cfg['Servers'][$i]['MaxTableUiprefs'] = 1000;

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '52740cdac68991.93232951';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['AllowArbitraryServer'] = true;
$cfg['LoginCookieStore'] = 2147483647;
$cfg['LoginCookieValidity'] = 2147483647;
$cfg['LoginCookieDeleteAll'] = false;
$cfg['PersistentConnections'] = true;
$cfg['ExecTimeLimit'] = 900;
$cfg['QueryHistoryDB'] = true;
$cfg['QueryHistoryMax'] = 500;
$cfg['MaxCharactersInDisplayedSQL'] = 10000;
$cfg['RetainQueryBox'] = true;
$cfg['SQLQuery']['ShowAsPHP'] = false;
$cfg['NavigationTreeDbSeparator'] = '';
?>